-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.picture_questions (
  id uuid primary key default gen_random_uuid(),
  answer text not null,
  aliases text[] not null default '{}',
  category text not null check (category in ('School/LGU & Local Culture','Places & Landmarks','Animals & Nature','General Knowledge')),
  difficulty text not null check (difficulty in ('Easy','Medium','Hard')),
  hint text not null default '',
  image_url text not null,
  image_path text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.game_settings (
  id bigint generated by default as identity primary key,
  seconds_per_question integer not null default 20 check (seconds_per_question between 5 and 120),
  starting_lives integer not null default 3 check (starting_lives between 1 and 10)
);
insert into public.game_settings(seconds_per_question,starting_lives)
select 20,3 where not exists(select 1 from public.game_settings);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.picture_questions enable row level security;
alter table public.game_settings enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_game_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users where user_id=auth.uid());
$$;
grant execute on function public.is_game_admin() to authenticated;

create policy "public read active questions" on public.picture_questions
for select to anon,authenticated using(is_active=true);
create policy "admins manage questions" on public.picture_questions
for all to authenticated using(public.is_game_admin()) with check(public.is_game_admin());

create policy "public read settings" on public.game_settings
for select to anon,authenticated using(true);
create policy "admins manage settings" on public.game_settings
for all to authenticated using(public.is_game_admin()) with check(public.is_game_admin());

insert into storage.buckets(id,name,public) values('game-images','game-images',true)
on conflict(id) do update set public=true;

create policy "public view game images" on storage.objects
for select to public using(bucket_id='game-images');
create policy "admins upload game images" on storage.objects
for insert to authenticated with check(bucket_id='game-images' and public.is_game_admin());
create policy "admins update game images" on storage.objects
for update to authenticated using(bucket_id='game-images' and public.is_game_admin())
with check(bucket_id='game-images' and public.is_game_admin());
create policy "admins delete game images" on storage.objects
for delete to authenticated using(bucket_id='game-images' and public.is_game_admin());

-- After creating an administrator in Supabase Authentication:
-- insert into public.admin_users(user_id) values('AUTH-USER-UUID');
